version: "3.7"

services:
  web:
    image: node:14
    ports:
      - "80:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    command: >
      bash -c "echo 'const http = require(\"http\");
      http.createServer((req, res) => res.end(\"Hola mundo\")).listen(3000);'
      > index.js && node index.js"
